name: Build Docker Image

on: workflow_dispatch

jobs:
  # Builds and pushes a docker image
  build_docker:
    runs-on: ubuntu-latest
    name: Build Docker Image

    steps:
      - uses: actions/checkout@v2
        name: Checkout master branch
        with:
          ref: master

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: plahner:latest
