# This is a basic workflow that is manually triggered

name: Deployment Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the backend
  build_backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout Backend

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build Backend
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Test Backend
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

  # Run a sonar-scan on the job
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout Backend
        with:
          fetch-depth: 0

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Generate test coverage
        uses: borales/actions-yarn@v2.3.0
        with:
            cmd: run test:cov

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check directories
        run: ls
      
