# This is a basic workflow that is manually triggered

name: Deployment Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      merge:
        description: Should a merge into master happen?
        default: "true"
        required: false

      increment:
        description: Should the version be incremented?
        default: "true"
        required: false

      release_step:
        description: What is the release step (if the version should be incremented)?
        default: "major"
        required: false

      tag:
        description: Should the master branch be tagged with the new version?
        default: "true"
        required: false

      build_docker:
        description: Should a new docker image be built?
        default: "true"
        required: false

      deploy:
        description: Should a new version be deployed on the server?
        default: "true"
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the backend
  build_backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and Test Backend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        name: Checkout Backend

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build Backend
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Test Backend
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

  # Run a sonar-scan on the job
  sonar_scan:
    runs-on: ubuntu-latest
    name: Sonar Scan

    steps:
      - uses: actions/checkout@v2
        name: Checkout Backend
        with:
          fetch-depth: 0

      - name: Install node_modules
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Generate test coverage
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run test:cov

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Quality Gate
        run: bash scripts/check_quality_gate.sh https://sonarcloud.io ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 2

  # Increment version
  increment_version:
    runs-on: ubuntu-latest
    name: Increment version
    if: github.event.inputs.increment == 'true'
    needs:
      - build_backend
      - sonar_scan

    steps:
      - uses: actions/checkout@v2
        name: Checkout Backend

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Increment version
        run: python scripts/increment_version.py ${{ github.event.inputs.release_step }}

      - name: Commit changed file
        uses: stefanzweifel/git-auto-commit-action@v4.5.1
        with:
          commit_message: Incremented version
          file_pattern: package.json

  # Merge the develop branch to master
  merge_to_master:
    runs-on: ubuntu-latest
    name: Merge develop to master
    if: github.event.inputs.merge == 'true'
    needs:
      - increment_version

    steps:
      - uses: actions/checkout@master
        name: Checkout Backend

      - name: Merge develop to master
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: develop
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Tag the master branch with the current version
  tag_branch:
    runs-on: ubuntu-latest
    name: Tag master branch
    if: github.event.inputs.tag == 'true'
    needs:
      - merge_to_master

    steps:
      - uses: actions/checkout@v2
        name: Checkout master branch
        with:
          ref: master

      - name: Get version
        id: get_version
        run: 'echo ::set-output name=version::$(cat package.json | grep -oP ''(?<="version": ")[^"]*'')'

      - name: Tag master branch
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release of version ${{ steps.get_version.outputs.version }}
          commitish: master

  # Builds and pushes a docker image
  build_docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    if: github.event.inputs.build_docker == 'true'
    needs:
      - merge_to_master

    steps:
      - uses: actions/checkout@v2
        name: Checkout master branch
        with:
          ref: master

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build and push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/mahalde/plahner-backend:latest

  # Deploy Docker Image on server
  deploy_to_server:
    runs-on: ubuntu-latest
    name: Deploy on Server
    if: github.event.inputs.deploy == 'true'
    needs:
      - build_docker

    steps:
      - uses: actions/checkout@v2
        name: Checkout master branch
        with:
          ref: master

      - name: Deploy Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            #!/usr/bin/env bash

            su - docker

            echo ${{ secrets.REPO_TOKEN }} | docker login ghcr.io -u mahalde --password-stdin

            docker pull ghcr.io/mahalde/plahner-backend:latest

            docker stop plahner-backend
            docker rm plahner-backend
            docker run -dp 80:3000 --name plahner-backend ghcr.io/mahalde/plahner-backend:latest
