name: Tag Branch

on: workflow_dispatch

jobs:
  # Tag the master branch with the current version
  tag_branch:
    runs-on: ubuntu-latest
    name: Tag master branch

    steps:
      - uses: actions/checkout@v2
        name: Checkout master branch
        with:
          ref: master

      - name: Get version
        id: get_version
        run: 'echo ::set-output name=version::$(cat package.json | grep -oP ''(?<="version": ")[^"]*'')'

      - name: Tag master branch
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release of version ${{ steps.get_version.outputs.version }}
